### ISSUE TITLE
Hero nyangkut bila dekat semak dan batu 

### ISSUE THREAD

**Issue by Ocyro** [GameLevelOne/JavataleIssues#10]
Character sering stag saat dket dg semak atau batu besar. Kadang sering nongol animasi "ambil" semak ato batu, dg sendirinya pdahal kita tidak ingin mengambil. Saat posisi duduk, sering stag dlm kondsi duduk (tdk mau balik ke posisi berdiri)
Procedure :  sering di stage 01,02 dan 03 
Expected result : dibedakan hit detect antara semak dan batu

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.16
