### ISSUE TITLE
No Sound on dirt and stone and water

### ISSUE THREAD

**Issue by motlevelone** [GameLevelOne/JavataleIssues#101]
No Sound or sound too little on dirt and stone and water

Steps:
1. Steps on dirt, or stone, or water
2. see the volume difference when walking on grass

Expected:
same volume level with walking on grass

v0.0.25

**Comment by BhaktiGL1** [comment]
Fixed in version v0.0.27

**Comment by BhaktiGL1** [comment]
Fixed in version v0.0.27
