### ISSUE TITLE
Collider on 3-1 cave entrance need adjustment

### ISSUE THREAD

**Issue by motlevelone** [GameLevelOne/JavataleIssues#102]
Weird collider position on cave entrance 3-1

Steps:
1. Destroy cave entrance on 3-1
2. Try to enter from top position

Expected:
More natural collider position

v0.0.25

**Comment by dennisgl1** [comment]
replace asset

**Comment by dennisgl1** [comment]
fixed in v0.0.26

**Comment by motlevelone** [comment]
Wrong asset

**Comment by dennisgl1** [comment]
optimized in v0.0.27

**Comment by GL1Elwin** [comment]
checked in v28
