### ISSUE TITLE
Big Summon didn't use mana

### ISSUE THREAD

**Issue by motlevelone** [GameLevelOne/JavataleIssues#106]
Big summon didn't consume mana

Steps:
1. Use Big Summon
2. See that mana is not decreased

Expected:
Mana decreased a lot

v0.0.25

**Comment by BhaktiGL1** [comment]
Fixed in version v0.0.26

**Comment by GL1Elwin** [comment]
checked in v26

**Comment by GL1Elwin** [comment]
checked in v26
