### ISSUE TITLE
Bomb didn't trigger beehive hit animation

### ISSUE THREAD

**Issue by motlevelone** [GameLevelOne/JavataleIssues#108]
Steps:
1. Put bomb near beehive
2. Wait for bomb to explode

Expected:
Beehive animation hit triggered when bomb explode

v0.0.25

**Comment by BhaktiGL1** [comment]
Fixed in version v0.0.26

**Comment by GL1Elwin** [comment]
checked in v26

**Comment by GL1Elwin** [comment]
checked in v26
