### ISSUE TITLE
Dash attack cannot activate when near wall

### ISSUE THREAD

**Issue by motlevelone** [GameLevelOne/JavataleIssues#116]
Steps:
1. Face close to wall or map edges
2. Use Dash attack

Expected:
Still charging dash and then bounced

v0.0.25

**Comment by BhaktiGL1** [comment]
The bug cannot reproduce, maybe because the player does not has enough mana to use boots

**Comment by BhaktiGL1** [comment]
Fixed in version v0.0.27

**Comment by GL1Elwin** [comment]
checked in v28
