### ISSUE TITLE
Big Summon cannot damage Jatayu

### ISSUE THREAD

**Issue by motlevelone** [GameLevelOne/JavataleIssues#117]
Steps:
1. Go to Jatayu
2. Use big summon

Expected:
Jatayu damaged by big summon

v0.0.25

**Comment by dennisgl1** [comment]
fixed in v0.0.26

**Comment by GL1Elwin** [comment]
still happen sometimes

**Comment by dennisgl1** [comment]
jatayu is invulnerable in certin state

**Comment by GL1Elwin** [comment]
checked in v28
