### ISSUE TITLE
Bomb get left behind when player pick it up and walk

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#127]
**Ver**
0.026

**Procedure**
1. Drop a bomb
2. Pick it up
3. walk

the bomb will stay behind and player stuck in lifting mode

bonus:
if player try to throw when stuck in lifting mode, the throw animation plays but then the player can no longer move

**Expected result**
the player should be able to carry the bomb while walking

![ss01](https://user-images.githubusercontent.com/26596324/47276870-ac03f380-d5e4-11e8-8068-7c28e81c60d3.png)

**Comment by BhaktiGL1** [comment]
Fixed in version v0.0.27

**Comment by GL1Elwin** [comment]
checked in v27
