### ISSUE TITLE
Missing assets in 3-1

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#129]
**Ver**
0.026

**Procedure**
1. Enter area 3-1
2. check the cave where player should bomb

**Expected results**
there should be assets covering the entry way

![ss01](https://user-images.githubusercontent.com/26596324/47276967-82979780-d5e5-11e8-89f8-4ec02bda7980.png)

**Comment by dennisgl1** [comment]
fixed in v0.0.27

**Comment by GL1Elwin** [comment]
issue persist

**Comment by dennisgl1** [comment]
fixed in v0.0.28

**Comment by GL1Elwin** [comment]
checked in v28
