### ISSUE TITLE
Attack action stuck

### ISSUE THREAD

**Issue by RoroFlora** [GameLevelOne/JavataleIssues#13]
Procedure:
When we got attacked by ghost (in the early stage 3 with 3 monkeys), without hitting the ghost first, the attack button can no longer be used/isn't working. The bug usually triggers in front of the treasure box or nearby.
Another way to trigger the bug is to attack (grass) in front of the chest.

Expected result:
Attack action become available again without having to go to another scene to refresh.

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.15
