### ISSUE TITLE
Replace old enemy hit asset

### ISSUE THREAD

**Issue by RoroFlora** [GameLevelOne/JavataleIssues#130]
Enemy hit "exclamation mark" asset still not yet changed.

![image](https://user-images.githubusercontent.com/31434530/47277354-b1177180-d5e9-11e8-8fc3-5c56183657b5.png)

New Asset:
![exclamation mark](https://user-images.githubusercontent.com/31434530/47277356-b674bc00-d5e9-11e8-9202-9e88e0fd1a32.png)

**Comment by BhaktiGL1** [comment]
version ?
