### ISSUE TITLE
Big summon have inconsistent size depends on the area

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#136]
**Ver**
0.027

**Procedure**
Cast big summon in the following area
the size is inconsistent
![ss01](https://user-images.githubusercontent.com/26596324/47333604-b76f2180-d6ad-11e8-8151-72ba4d2e7a57.png)
Area 3-1
![ss02](https://user-images.githubusercontent.com/26596324/47333605-b76f2180-d6ad-11e8-9d9f-0ed1f163514e.png)
Area 2-1
![image](https://user-images.githubusercontent.com/26596324/47333907-fc478800-d6ae-11e8-8474-53b165da60d7.png)
Jatayu
**Expected result**
Should be consistent

**Comment by BhaktiGL1** [comment]
Fixed in version v0.0.28
