### ISSUE TITLE
UI Health bar

### ISSUE THREAD

**Issue by JohanesMardhika** [GameLevelOne/JavataleIssues#15]
**Procedure**
Bagian UI Health bar kurang terasa hidup, sehingga terasa menyatu dengan background/environment

**Expected result**
mungkin bisa ditambahkan efek _glowing_ yang lebih terang pada "health bar". dan lebih terlihat menjadi satu kesatuan dengan UI item yang ada disebelahnya.

**Comment by motlevelone** [comment]
fix on v0.0.18
