### ISSUE TITLE
Proofread 

### ISSUE THREAD

**Issue by waygl1** [GameLevelOne/JavataleIssues#17]
We have read through the dialogue, here's a little revision you might want to consider
Thank you

A: So we’re here, just like I promised to you
    And…
    Oh… Perfect. 
    I was gone for five minutes and somebody stole all the colors from here
    Naturally, I do not think YOU had anything to do with it
    I’m preeeetty sure it is just a coincidence that you came here   
    AFTER some MYSTERIOUS person passed through here 
    Looks like they are heading to the temple of DOOM 
    DOOM, I TELL YOU!
    DOOOOOOMMM!!
    Heh...Heh...Heh…
    …
    Still going there? (**Still want to go there?**)
    FINE!! (**So be it!**)
    I can only guide you so far
    Only crazyest people would go to the temple (**Only craziest people would go to the temple**) 
    And they told me I’M crazy
    which I’m no...
    I’ll be waiting here right on the edge
    In case I need to run from you know…
    Monsters…

**Comment by GL1Elwin** [comment]
@dennisgl1 just fix the 'craziest' part

**Comment by dennisgl1** [comment]
fixed in v0.0.16
