### ISSUE TITLE
Monster Bug

### ISSUE THREAD

**Issue by AndreasHaryono96** [GameLevelOne/JavataleIssues#19]
Procedure:
Pada scene "abandoned clearing" saya mendapati karakter tidak diserang oleh monster. Situasi ini terjadi saat user tidak melakukan action apa pun seperti berjalan melewati monster tersebut. Monster akan menyerang user apa bila sprite karakter user mengenai sprite karakter monster.

<img width="960" alt="bug01" src="https://user-images.githubusercontent.com/43771193/46343903-86c93880-c669-11e8-9889-cd3e9d2ce033.png">

Expected result:
Ketika user mencoba mendekati monster, seharusnya monster langsung menyerang user. Seperti monster-monster pada scene sebelumnya.

**Comment by dennisgl1** [comment]
monster monkey ini tidak akan menyerang player sampai player melakukan _hit_ ke monkey atau menabrak monkey.
