### ISSUE TITLE
Missing fish shadow for mini game

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#2]
**Procedure:**
Enter area 3-1 and check the river, there should be shadow of fish so player can start the mini game

**Expected result:**
There are fish in the water at area 3-1 & 3-3

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.16

**Comment by GL1Elwin** [comment]
can we have it in darker color? (dark grey/black)

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.19

**Comment by GL1Elwin** [comment]
checked in v19
