### ISSUE TITLE
Lotus attack rate to fast

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#24]
**Ver**
0.012

**Procedure**
visit area 3 and watch the lotus shoot

**Suggestion**
decrease fire rate so player can attack them using bow

**Comment by dennisgl1** [comment]
fixed in v0.0.16

**Comment by GL1Elwin** [comment]
need to be a little bit slower

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.19

**Comment by GL1Elwin** [comment]
checked in v19
