### ISSUE TITLE
Ultimate skill wont kill the monsters + only "gatot kaca" effect that come out

### ISSUE THREAD

**Issue by waygl1** [GameLevelOne/JavataleIssues#27]
Procedure : 
- Every time i use the ultimate skill, it has no effect on any monsters, any monsters wont die.

- Before, in prototype v.0.0.13 when i used the ultimate skill, after "gatot kaca" effect came out there was this sphere kind of effect came after that, but i don't find it in the newest version [v.0.0.16]

**Comment by BhaktiGL1** [comment]
fixed in v0.0.17
