### ISSUE TITLE
Bug pada syal hero

### ISSUE THREAD

**Issue by AndreasHaryono96** [GameLevelOne/JavataleIssues#29]
Procedure: Saya mendapati bug pada selendang/syal biru pada hero utama yang tidak utuh. Bug ini akan didapatkan user ketika karakter user terkena serangan musuh, semakin terkena serangan musuh maka selendang/syal akan menyusut/hilang. (Ver 0.16)

<img width="960" alt="bug04" src="https://user-images.githubusercontent.com/43771193/46600660-16149700-cb15-11e8-90b4-2dcdb9686541.png">

![Uploading Bug05.png…]()

Expected Result: Selendang/syal seharusnya dalam keadaan utuh.

**Comment by GL1Elwin** [comment]
By design

**Comment by dennisgl1** [comment]
@AndreasHaryono96 syal represent Player's health.

**Comment by AndreasHaryono96** [comment]
@dennisgl1 Okay, but i think user need to know that feature. I have an article, i hope this will help. https://yuxingw.wordpress.com/2017/04/27/the-usage-of-loading-time/

**Comment by dennisgl1** [comment]
@GL1Elwin keputusan?

**Comment by GL1Elwin** [comment]
will make a tutorial in dsign post
