### ISSUE TITLE
Border issue

### ISSUE THREAD

**Issue by AndreasHaryono96** [GameLevelOne/JavataleIssues#30]
Procedure: Minimalis/tidak adanya border pada skill bar, berpengaruh pada keterjelasan user untuk melihat icon-icon skill secara nyaman dan kurangnya konsistensi pada penggunaan border.

<img width="960" alt="suggest" src="https://user-images.githubusercontent.com/43771193/46603150-73601680-cb1c-11e8-91a7-1d1b23b2344f.png">

Expected Result:
-Menurut pendapat saya sebagai desainer, keterjelasan dan kenyamanan user saat bermain sangatlah penting. Perlu adanya penambahan border pada skill bar, yang tujuannya agar icon-icon skill jelas terlihat.
-Dan selain itu penggunaan daun-daun pada tiap corner game perlu diperhatikan juga nilai estetiknya, dikhawatirkan dapat mengurangi kenyamanan user dalam bermain, sebaiknya jangan terlalu besar dan jangan terlalu kecil dan tetap menjaga konsistensi pada border lainnya.

![rf-online-mech](https://user-images.githubusercontent.com/43771193/46603156-778c3400-cb1c-11e8-8876-5bf986598bae.jpg)

![maxresdefault](https://user-images.githubusercontent.com/43771193/46603167-7a872480-cb1c-11e8-940d-4bc9cc7342b2.jpg)

**Comment by dennisgl1** [comment]
@GL1Elwin @motlevelone

**Comment by motlevelone** [comment]
This enhancement seems won't be done for current target. Is this okay @GL1Elwin ?

**Comment by GL1Elwin** [comment]
Under advisement. Next!
