### ISSUE TITLE
Swing Sfx doesn't play when player facing right

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#33]
**Ver**
0.017

**Procedure**
Face right and swing sword, the swing sounds are missing (they can be hear when the player facing up, left, and down)
this only occurs of left speaker

**Expected result**
there are sounds when the player facing right on both speaker

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.19

**Comment by GL1Elwin** [comment]
Checked in v19
