### ISSUE TITLE
Bomb appears underneath rock

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#41]
**Ver**
0.017

**Procedure**
Go to area 3-1 to blocked cave entrance, place  a bomb exactly in front of the rocks
The bomb will appear UNDER the rocks

**Expected result**
The bomb should appear on top of the rocks

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.19

**Comment by GL1Elwin** [comment]
checked in ver 21
