### ISSUE TITLE
Ground Color Difference in Area 3

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#42]
**Ver**
0.017

**Procedure**
Go to area 3-1 where the grounds meets the river

**Expected result**
Color should be consistend

![bug01](https://user-images.githubusercontent.com/26596324/46658930-0c0a9b00-cbde-11e8-9de7-9e9404d37d0d.png)

**Comment by GL1Elwin** [comment]
checked in v19

**Comment by GL1Elwin** [comment]
still exist, on the ground near cave

**Comment by dennisgl1** [comment]
check again v0.0.24
- provide screenshot if available

**Comment by GL1Elwin** [comment]
checked in v24
