### ISSUE TITLE
Missing fishing bob

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#43]
**Ver**
0.017

**Procedure**
After obtaining the fishing rod go to area 3-1 where there's a shadow of a fish or any river then cast a line
nothing appear on water

**Expected result**
the fishing bob should appear and attract the fish

![bug02](https://user-images.githubusercontent.com/26596324/46659147-93580e80-cbde-11e8-8b70-f3d5417a88c7.jpg)

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.19

**Comment by GL1Elwin** [comment]
still missing

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.20

**Comment by GL1Elwin** [comment]
still missing

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.22

**Comment by GL1Elwin** [comment]
nope, still happen

**Comment by BhaktiGL1** [comment]
Play using Medium Quality in version 0.0.25

**Comment by GL1Elwin** [comment]
checked in v28
