### ISSUE TITLE
Rock should be destroyable using bombs

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#47]
**Ver**
0.019

**Procedure**
Place bombs near rock and observe
the bomb does not harm the rock but player are expected to think that the rock can destroy a cave wall

**Suggestion**
Bomb should be able to destroy rock as well

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.20

**Comment by GL1Elwin** [comment]
checked in ver 21
