### ISSUE TITLE
Ghost in 2-2 can sometimes go through boundaries when aggroed

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#48]
**Ver**
0.019

**Procedure**
Go near the tress on the left side when player enters from 2-1,
Wait until pc in agro range of ghost, watch the ghost go past the trees

**Expected result**
rock should not go through the tree

**Comment by dennisgl1** [comment]
resolved by:
- reducing ghost vigilance range
- reducing ghost patrol range
build v0.0.20

**Comment by GL1Elwin** [comment]
checked in ver 21
