### ISSUE TITLE
Wrong BGM plays AFTER cutscene 2-2

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#50]
**Ver**
0.019

**Procedure**
Trigger 2-2 cutscene until it finishes, listen to the bgm.. forest bgm still playes

**Expected result**
different bgm (musik seru) should play after this sequence

**Comment by dennisgl1** [comment]
fixed in v0.0.20

**Comment by GL1Elwin** [comment]
checked in ver 21
