### ISSUE TITLE
Player go through  the bottom of the cliff near the cave entrrance

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#51]
**Ver**
0.019

**Procedure**
Enter the cave, or exit the cave

**Expected result**
the player should appear to enter and exit the cave realistically

**Comment by dennisgl1** [comment]
resolved by moving the wall collider (invisible) at the top side of cave entrance slightly lower.
v 0.0.20

**Comment by GL1Elwin** [comment]
checked in v.21
