### ISSUE TITLE
Player can move around during 1st time tutorial

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#52]
**Ver**
0.019

**Procedure**
Start the game, after the cutscene, when the tutorial sign post appear, try moving the player

**Expected result**
The game should be paused when viewing message like this

**Comment by motlevelone** [comment]
Should've not happen. Please try again at v0.0.21

**Comment by GL1Elwin** [comment]
you can hear the sounds of the steps

**Comment by GL1Elwin** [comment]
checked in v24
