### ISSUE TITLE
Loots disappear too fast!

### ISSUE THREAD

**Issue by RoroFlora** [GameLevelOne/JavataleIssues#53]
Loots like mana or money disappears too soon. Like when I was busy killing hoards of bees and when I'm done, the loots are gone already.

Expected result:
I want more time to get the loots after killing enemies.

**Comment by GL1Elwin** [comment]
I second this

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.22

**Comment by GL1Elwin** [comment]
checked in v 22
