### ISSUE TITLE
Uneven/mismatched color terrain

### ISSUE THREAD

**Issue by RoroFlora** [GameLevelOne/JavataleIssues#55]
Are these possible to be fixed?

![image](https://user-images.githubusercontent.com/31434530/46848828-3ba3e800-ce16-11e8-8a65-703c3ebff32b.png)

![image](https://user-images.githubusercontent.com/31434530/46848837-4cecf480-ce16-11e8-8159-68fb151a70bd.png)

**Comment by dennisgl1** [comment]
fixed in v0.0.24
