### ISSUE TITLE
stuck saat selesai mengalahkan jatayu

### ISSUE THREAD

**Issue by JohanesMardhika** [GameLevelOne/JavataleIssues#56]
Ver
0.020

**Procedure**
efek "skill suara jatayu" tidak hilang sampai end game. setelah mengalahkan jatayu, scene tidak berganti ke "to be continue" / stuck.

**Expected result**
efek skill suara jatayu hilang saat jatayu kalah. dan tidak stuck lagi di ending scene.

**Comment by dennisgl1** [comment]
coba lagi v0.0.24
