### ISSUE TITLE
Random rock break sfx playing in the game

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#58]
**Ver**
0.021

**Procedure**
Play the game, listen closely
This occurs when enemies accidentally hit a stationary rocks - it hits the enemies and the rock broke

**Expected result**
Rock break sfx should not play randomly.

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.22

**Comment by GL1Elwin** [comment]
checked in v22
