### ISSUE TITLE
mising graffix on top border in area 1-1 and 2-1

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#59]
**Ver**
0.021

**Procedure**
Try leaving area 1-1 towards 2-1
and area 2-1 towards 2-2

there's a blue area indicating a missing graphcics
**Expected result**
there shouldn't be a blue area

**Comment by dennisgl1** [comment]
fixed in v0.0.22

**Comment by GL1Elwin** [comment]
checked in 22
