### ISSUE TITLE
Stone lifted even there is no stone in the area.

### ISSUE THREAD

**Issue by Hanamura0** [GameLevelOne/JavataleIssues#6]
Procedure:

After throwing the stones, in the same place where the stone was, the hero will lifted another stone even there is no stone there. Sometimes, when I lift a stone and I throw it, without moving, I press the button to lift, and the stone that I throw will be in my hands again.
It happens sometimes in the early map area, tested it several times, sometimes it occurred, sometimes it is not.

Expected:
After throwing the stones away, the initial area of the stone should be empty.

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.15
