### ISSUE TITLE
Player & enemies should be the focus during slow mo dodging

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#60]
**Ver**
0.021

**Procedure**
face the enemy, dodge the enemy attack

**Expected result**
the motion blur should center on the player so the player have clearer focus

reference
![lozbotw_0007_layer_7](https://user-images.githubusercontent.com/26596324/46929098-0bec1e80-d068-11e8-91a7-d206d6d8e02d.jpg)

**Comment by BhaktiGL1** [comment]
Fixed in version v0.0.27

**Comment by GL1Elwin** [comment]
checked in v27
