### ISSUE TITLE
During the slow motion sequence, which button to press should be visible

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#61]
**Ver**
0.021

**Procedure**
face the enemy, dodge the enemy attack. Observe the insruction

**Expected result**
the button should be clear to the player

![lozbotw_0007_layer_7](https://user-images.githubusercontent.com/26596324/46929162-5a012200-d068-11e8-94bc-d0ab64b30001.jpg)

**Comment by BhaktiGL1** [comment]
Fixed in version v0.0.27

**Comment by GL1Elwin** [comment]
checked in v27
