### ISSUE TITLE
In Main Title if you press the tool button you can hear the sound of the bomb drop and explode

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#64]
**Ver**
0.022

**Procedure**
Start the game, press the use tool button, or any button.
You can hear the sound of the action being played

**Expected result**
This shouldn't happen, can confuse the player

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.24

**Comment by GL1Elwin** [comment]
checked in v24
