### ISSUE TITLE
Key stuck at player feet

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#65]
**Ver**
0.022

**Procedure**
Visit Area 2-2, Defeat the ghot and open the chest,
after receiving the key, the key stuck at the player's feet

also happen with fire arrow

**Expected result**
THis shouldn't happen

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.23

**Comment by GL1Elwin** [comment]
checked in v.23
