### ISSUE TITLE
Screen Freeze after dark monster cutscene

### ISSUE THREAD

**Issue by Hanamura0** [GameLevelOne/JavataleIssues#7]
Procedure:

After the cutscene, the hero freeze and when we try to move it, he wont move, but several seconds later, he will instantly transported  few blocks. It happens all the time when I enter the cutscene. 
and the transition before the cutscene is a bit laggy.

Expected: 

After the cutscene, there wont be screen freeze and you can move your hero directly.

**Comment by dennisgl1** [comment]
what version?
try in v0.0.16
@Hanamura0
