### ISSUE TITLE
No bomb sfx when explode

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#70]
**Ver**
0.022

**Procedure**
Drop a bomb, wait for it to explode
no sfx

**Expected result**
there should be a sfx indicating explosion, maybe doa camera shake as well

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.23

**Comment by GL1Elwin** [comment]
can't check if it can't explode

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.24

**Comment by GL1Elwin** [comment]
checked in v24
