### ISSUE TITLE
Cutscene produce loot

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#73]
**Ver**
0.023

**Procedure**
Go to area 2-2 and wait until the cutscene triggers

when the ghost appear, it cause them to hit the grass and produce loot
this happens because when the ghost appear, it destroy the grass near it

**Expected result**
Enemies should never produce loot during cutscene

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.24

**Comment by GL1Elwin** [comment]
checked in v24
