### ISSUE TITLE
Timing is off to perfect parry & perfect dodge

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#74]
**Ver**
0.023

**Procedure**
Fight an enemy, try to dodge or parry when the exclamation mark appears

**Expected result**
Player should b eable to do perfet dodge or perfect parry when the exclamation mark appears, and there's a split second window before & after it appears

**Comment by BhaktiGL1** [comment]
Updated in version 0.0.25

**Comment by GL1Elwin** [comment]
checked in v.25
