### ISSUE TITLE
Scarf in front of player during cutscene

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#75]
**Ver**
0.024

**Procedure**
Start the game and let the cutscene plays

![ss04](https://user-images.githubusercontent.com/26596324/47129118-2fa8a200-d2be-11e8-9f4b-ad1a0e5ea1e0.png)

**Expected result**
The scarf should be on PC's back no in front

![ss01](https://user-images.githubusercontent.com/26596324/47129124-359e8300-d2be-11e8-914b-71ba22dad98f.png)
![Uploading ss02.png…]()

**Comment by dennisgl1** [comment]
screenshot

**Comment by BhaktiGL1** [comment]
Fixed in version v0.0.27

**Comment by GL1Elwin** [comment]
checked in v27
