### ISSUE TITLE
Shadow intensity should be higher

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#76]
**Ver**
0.024

**Procedure**
Play the game and observer the shadow

**Expected result**
The shadow intensity should be higher

**Comment by Ocyro** [comment]
![opsi_shadow hero 01](https://user-images.githubusercontent.com/43770755/47129729-bbbbc900-d2c0-11e8-8d5b-df29f06554af.jpg)

**Comment by dennisgl1** [comment]
shadow strength settings is now doubled in v0.0.25

**Comment by GL1Elwin** [comment]
can be a bit sharper

**Comment by GL1Elwin** [comment]
seen in v.26
