### ISSUE TITLE
Bombs blast radius too small 

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#77]
**Ver**
0.024

**Procedure**
Place bombs near enemy

**Expected result**
Bombs should damage enemy around this area
![ss04](https://user-images.githubusercontent.com/26596324/47129564-f40ed780-d2bf-11e8-983f-a9e96aec9453.png)

**Comment by BhaktiGL1** [comment]
Bigger bomb blast radius in version 0.0.25

**Comment by GL1Elwin** [comment]
checked in v.25
