### ISSUE TITLE
During the leaf attack the sfx plays too soon and it need a effect

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#79]
**Ver**
0.024

**Procedure**
Play against jatayu and wait for it to do the leaf attack, the sound play too soon

**Expected result**
The sfx should play when it is 'charging' (the wings close together) and should display a effect (something like a circle became close indicating the time of attack)

**Comment by GL1Elwin** [comment]
for effect I think the circle effect when the bomb exploded but played in reverse should do the trick

**Comment by dennisgl1** [comment]
added in v0.0.25

**Comment by GL1Elwin** [comment]
checked in v.25
