### ISSUE TITLE
There should be a difference of the leaf attack when Jatayu have less than 50% HP

### ISSUE THREAD

**Issue by GL1Elwin** [GameLevelOne/JavataleIssues#80]
**Ver**
0.024

**Procedure**
Play against jatayu and wait for it to do the leaf attack when it have less than 50% HP

**Expected result**
The attack should be difference as well, may be throw the leaf attack 2-3 times and changing angle (llike in shooter game)

**Comment by dennisgl1** [comment]
added in v0.0.25

**Comment by GL1Elwin** [comment]
checked in v.25
