### ISSUE TITLE
Enemy spawn looks weird

### ISSUE THREAD

**Issue by RoroFlora** [GameLevelOne/JavataleIssues#83]
Ghost keep running towards the rock, it looks buggy

![image](https://user-images.githubusercontent.com/31434530/47149447-c9437400-d2fd-11e8-8fd7-18483d733ec4.png)

![image](https://user-images.githubusercontent.com/31434530/47149467-d52f3600-d2fd-11e8-8b29-689bfbf55b72.png)

**Comment by dennisgl1** [comment]
fixed on v0.0.26
