### ISSUE TITLE
Nyangkut pas angkat batu

### ISSUE THREAD

**Issue by cynchann** [GameLevelOne/JavataleIssues#9]
Procedure : lokasinya bisa beda2 (yang paling sering terjadi di scene 1 dan scene 3 deket peti yg ada kunci, yang deket peti gaada batu tau2 nyangkut). kalau uda nyangku ga bisa ngapa2in lagi cuma bisa exit
Expected result :  tidak nyangkut lagi pas angkat batu

**Comment by BhaktiGL1** [comment]
Fixed in version 0.0.15
