### ISSUE TITLE
Need bigger monkey aggro area

### ISSUE THREAD

**Issue by motlevelone** [GameLevelOne/JavataleIssues#93]
Monkey Aggro area (when other monkey is attacked), seems too small, so most of the time it's not aggroing the player

Steps:
1. Attack a monkey
2. check other monkey within the same screen

Expected:
Monkey within same screen will aggro player

v0.0.25

**Comment by BhaktiGL1** [comment]
Fixed in version v0.0.26

**Comment by dennisgl1** [comment]
fixed in v0.0.26
