### ISSUE TITLE
Full health but scarf still battered

### ISSUE THREAD

**Issue by motlevelone** [GameLevelOne/JavataleIssues#94]
![health_scarf](https://user-images.githubusercontent.com/26595174/47196734-4289a800-d38c-11e8-9b01-1d84cd4fce01.png)

Steps:
1. Get some damage on player
2. Heal to full from item drop

Expected:
At full Health, the scarf should also full

v0.0.25

**Comment by BhaktiGL1** [comment]
Fixed in version v0.0.26
